### ISSUE TITLE
Cannot Run it on Windows 19.03

### ISSUE THREAD

**Issue by amanszpapaya** [d00rt/ebfuscator#2]
Hi,

I could not able to run the ebfuscator on Windows 19.03. I have tried it on both Windows cmds(SYSWOW64 and norma cmd) and Powershell. Can you help ?

Thanks
![Screen Shot 2020-04-29 at 12 36 10](https://user-images.githubusercontent.com/40626848/80581574-02da5c80-8a16-11ea-944e-a458fad7f52a.png)

**Comment by d00rt** [comment]
Are you sure the problem is on my side? Please read the output of the errors! You have 2
1) Says you entered a ">" character before the command
2) Says you changed the extension from ebfuscator.exe to ebfuscator.bin then windows doesn't recognize the file extension and it doesn't run

**Comment by amanszpapaya** [comment]
Sorry I have attached the wrong image you can find the correct below:

![Screen Shot 2020-04-29 at 16 31 43](https://user-images.githubusercontent.com/40626848/80601940-2792fc00-8a37-11ea-83b7-87a8450f1cc3.png)

**Comment by d00rt** [comment]
you are running on windows, the program was compiled for linux

**Comment by amanszpapaya** [comment]
Ooh ok, I thought since it obfuscates Windows I can run it on Windows too, my bad thanks
